"""Initial

Revision ID: 97f1c50fa6e4
Revises: 
Create Date: 2024-11-15 00:46:15.409305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97f1c50fa6e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchangetransaction',
        sa.Column('status', sa.Enum('initial', 'paid', name='transactionstatus'), nullable=False),
        sa.Column('receive_currency', sa.String(length=10), nullable=False),
        sa.Column('send_currency', sa.String(length=10), nullable=False),
        sa.Column('receive_network', sa.String(length=50), nullable=False),
        sa.Column('send_network', sa.String(length=50), nullable=False),
        sa.Column('receive_address', sa.String(length=100), nullable=False),
        sa.Column('exchange_id', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.BigInteger(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('exchange_id')
    )
    op.create_index(op.f('ix_exchangetransaction_id'), 'exchangetransaction', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchangetransaction_id'), table_name='exchangetransaction')
    op.drop_table('exchangetransaction')
    # ### end Alembic commands ###
